name: Build, Test & Deploy to NuGet

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Deploys only on version tags like v1.0.0

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: src

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      working-directory: src

    - name: Pack NuGet package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
            RAW_VERSION="${{ github.ref_name }}"
            VERSION="${RAW_VERSION#v}"  # strips leading 'v'
            echo "Packing version $VERSION"
            dotnet pack --configuration Release /p:PackageVersion=$VERSION --output ./nupkgs
      working-directory: src

    - name: Push to NuGet
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      working-directory: src